<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <title>Warsztaty Kryptoksięgowość</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="apple-touch-icon" href="/pages/ico/60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/pages/ico/76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/pages/ico/120.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/pages/ico/152.png">
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/assets/plugins/pace/pace-theme-flash.css" rel="stylesheet" type="text/css" />
    <link href="/assets/plugins/boostrapv3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/plugins/font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css" />
    <link href="/assets/plugins/jquery-scrollbar/jquery.scrollbar.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/assets/plugins/bootstrap-select2/select2.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/assets/plugins/switchery/css/switchery.min.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/pages/css/pages-icons.css" rel="stylesheet" type="text/css">
    <link class="main-stylesheet" href="/pages/css/pages.css" rel="stylesheet" type="text/css" />
    <!--[if lte IE 9]>
    <link href="/pages/css/ie9.css" rel="stylesheet" type="text/css" />
    <![endif]-->
    <script type="text/javascript">
        window.onload = function()
        {
            // fix for windows 8
            if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
                document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="pages/css/windows.chrome.fix.css" />'
        }
    </script>
</head>
    <style>
        body {
            font-family: Helvetica, Arial, sans-serif;
            margin: 0;
        }

        h1 {
            font-size: 20px;
        }


        .qtip-bootstrap {
            font-size: 12px;
        }

        .free {
            fill: lightsteelblue;
        }

        .cc-selector input{
            margin:0;padding:0;
            -webkit-appearance:none;
            -moz-appearance:none;
            appearance:none;
        }

    </style>
</head>
<body class="fixed-header error-page  ">
<div class="container-xs-height full-height">
    <div class="row-xs-height">
        <div class="col-xs-height col-middle">
            <div class="error-container text-center" style="width: 80%">
                <div class="center" style="width: 100%; text-align: center;">
                    <img src="https://www.tradecoinclub.com/assets/images/bitcoins.png" alt="logo" style="max-width: 520px; margin: 10px auto;" class="img-responsive" data-src="https://www.tradecoinclub.com/assets/images/bitcoins.png" data-src-retina="https://www.tradecoinclub.com/assets/images/bitcoins.png" >
                </div>
				<h3 style="text-align: center; margin-top: 50px; color: #dca243; margin-bottom: 50px;"><span style="font-weight: 400">CRYPTO EXPO</span><br />20.09.2018 <span style="color: #000">Warszawa</span><br /><span style="color: #000">PGE Narodowy</span></h3>
				<?php if($_GET['error'] && $_GET['error'] == 501) { ?>
                    <h4 class="semi-bold text-danger">Niestety! Zakupiony bilet nie został poprawnie opłacony.</h3>
                    <h4 class="semi-bold">Zapraszamy do ponownego zakupu.</h3>
                <? } else { ?>
                    <h4 class="semi-bold text-success">Dziękujemy! Proces zamówienia biletu przebiegł prawidłowo.</h3>
                    <h4 class="semi-bold">Za chwilę na Twoją skrzynkę mailową wyślemy zakupiony bilet oraz dokument rozliczeniowy.</h3>
                <?php } /* ?>
				<h5 class="semi-bold"><br />Bądź na bieżąco, śledź nas na kanałach:<br />
					<a href="https://www.facebook.com/Healthy-LifeStyle-Show-128222207764351/" target="_blank"><img src="/images/if_Asset_1_2643199.png" alt="Facebook" style="width: 32px; height: 32px;"></a>
					<a href="https://www.instagram.com/healthy_lifestyle_show/" target="_blank"><img src="/images/if_Asset_2_2643234.png" alt="Facebook" style="width: 32px; height: 32px;"></a>
					<a href="https://twitter.com/HLShow2018" target="_blank"><img src="/images/if_Asset_12_2643226.png" alt="Facebook" style="width: 32px; height: 32px;"></a>
					<a href="https://www.youtube.com/channel/UCl_Y2FoPmNfgyqzGACNBydg" target="_blank"><img src="/images/if_Asset_11_2643227.png" alt="Facebook" style="width: 32px; height: 32px;"></a>
				</h5>*/ ?>
            </div>
        </div>
    </div>
</div>


<!-- END OVERLAY -->
<!-- BEGIN VENDOR JS -->
<script src="/assets/plugins/pace/pace.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="/assets/plugins/modernizr.custom.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="/assets/plugins/boostrapv3/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery/jquery-easy.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-unveil/jquery.unveil.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-bez/jquery.bez.min.js"></script>
<script src="/assets/plugins/jquery-ios-list/jquery.ioslist.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-actual/jquery.actual.min.js"></script>
<script src="/assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<script type="text/javascript" src="/assets/plugins/bootstrap-select2/select2.min.js"></script>
<script type="text/javascript" src="/assets/plugins/classie/classie.js"></script>
<script src="/assets/plugins/switchery/js/switchery.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<!-- END VENDOR JS -->
<!-- BEGIN CORE TEMPLATE JS -->
<script src="/pages/js/pages.min.js"></script>
<!-- END CORE TEMPLATE JS -->
<!-- BEGIN PAGE LEVEL JS -->
<script src="/assets/js/scripts.js" type="text/javascript"></script>
<!-- END PAGE LEVEL JS -->
<script>
    $(function()
    {
        $('#form-register').validate()
    })
</script>
</body>
</html>
