<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <title>CryptoExpo 2018</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="apple-touch-icon" href="/pages/ico/60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/pages/ico/76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/pages/ico/120.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/pages/ico/152.png">
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href="/assets/plugins/pace/pace-theme-flash.css" rel="stylesheet" type="text/css" />
    <link href="/assets/plugins/boostrapv3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/plugins/font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css" />
    <link href="/assets/plugins/jquery-scrollbar/jquery.scrollbar.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/assets/plugins/bootstrap-select2/select2.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/assets/plugins/switchery/css/switchery.min.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/pages/css/pages-icons.css" rel="stylesheet" type="text/css">
    <link class="main-stylesheet" href="/pages/css/pages.css" rel="stylesheet" type="text/css" />
    <!--[if lte IE 9]>
    <link href="/pages/css/ie9.css" rel="stylesheet" type="text/css" />
    <![endif]-->
    <script type="text/javascript">
        window.onload = function()
        {
            // fix for windows 8
            if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
                document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="pages/css/windows.chrome.fix.css" />'
        }
    </script>

</head>
    <style>
        body {
            font-family: Helvetica, Arial, sans-serif;
            margin: 0;
        }

        h1 {
            font-size: 20px;
        }


        .qtip-bootstrap {
            font-size: 12px;
        }

        .free {
            fill: lightsteelblue;
        }

        .cc-selector input{
            margin:0;padding:0;
            -webkit-appearance:none;
            -moz-appearance:none;
            appearance:none;
        }
        .ticket_1{background-image:url('/images/1_ticket.jpg');}
        .ticket_2{background-image:url('/images/2_ticket.jpg');}
        .ticket_3{background-image:url('/images/3_ticket.jpg');}
        .ticket_4{background-image:url('/images/4_ticket.jpg');}
        .ticket_5{background-image:url('/images/5_ticket.jpg');}

        .pomaranczowy {color: #ff5722}
        .pomaranczowyBg {background-color: #ff5722; color: #000}
        .niebieski {color: #0070c0}
        .niebieskiBg {color: #fff; background-color: #0070c0}
        .zolty {color: #ffc107}
        .zoltyBg {color: #000; background-color: #ffc107}
        .rozowy {color: fuchsia}
        .rozowyBg {background-color: fuchsia}
        .czerwony {color: red}
        .czerwonyBg {color: #fff; background-color: red}
        .zielony {color: #70ad47}
        .zielonyBg {color: #fff; background-color: #70ad47}
        .fioletowy {color: #7030a0}
        .fioletowyBg {color: #fff; background-color: #7030a0}

        .cc-selector input:active +.drinkcard-cc{opacity: .9;}
        .cc-selector input:checked +.drinkcard-cc{
            -webkit-filter: none;
            -moz-filter: none;
            filter: none;
        }
        .drinkcard-cc{
            cursor:pointer;
            background-size:contain;
            background-repeat:no-repeat;
            display:inline-block;
            width:155px;height:150px;
            -webkit-transition: all 100ms ease-in;
            -moz-transition: all 100ms ease-in;
            transition: all 100ms ease-in;
            -webkit-filter: brightness(1.2) grayscale(1) opacity(.6);
            -moz-filter: brightness(1.2) grayscale(1) opacity(.6);
            filter: brightness(1.2) grayscale(1) opacity(.6);
        }
        .drinkcard-cc:hover{
            -webkit-filter: brightness(1.2) grayscale(.5) opacity(.9);
            -moz-filter: brightness(1.2) grayscale(.5) opacity(.9);
            filter: brightness(1.2) grayscale(.5) opacity(.9);
        }

		.tooltip-inner {
			white-space: pre-wrap;
		}
    </style>
</head>
<body class="fixed-header   ">
<div class="register-container full-height sm-p-t-30" style="width: 75%;">
    <div class="container-sm-height full-height">
        <div class="row row-sm-height">
            <div class="col-sm-12 col-sm-height col-middle">
				<div class="right" style="width: 100%; text-align: right;">Zalogowany jako: <?php echo $role; ?></div>
                <div class="center" style="width: 100%; text-align: center;">
                    <img src="/images/CryptoFutureFinalExpoWhite.png" alt="logo" data-src="/images/CryptoFutureFinalExpoWhite.png" style="width: 60%" data-src-retina="/images/CryptoFutureFinalExpoWhite.png" >
                </div>
                <?php echo $content; ?>
            </div>
        </div>
    </div>
</div>

<!-- END OVERLAY -->
<!-- BEGIN VENDOR JS -->
<script src="/assets/plugins/pace/pace.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="/assets/plugins/modernizr.custom.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="/assets/plugins/boostrapv3/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery/jquery-easy.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-unveil/jquery.unveil.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-bez/jquery.bez.min.js"></script>
<script src="/assets/plugins/jquery-ios-list/jquery.ioslist.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-actual/jquery.actual.min.js"></script>
<script src="/assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<script type="text/javascript" src="/assets/plugins/bootstrap-select2/select2.min.js"></script>
<script type="text/javascript" src="/assets/plugins/classie/classie.js"></script>
<script src="/assets/plugins/switchery/js/switchery.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<!-- END VENDOR JS -->
<!-- BEGIN CORE TEMPLATE JS -->
<script src="/pages/js/pages.min.js"></script>
<!-- END CORE TEMPLATE JS -->
<!-- BEGIN PAGE LEVEL JS -->
<script src="/assets/js/scripts.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-validation/js/localization/messages_pl.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL JS -->
<script>
    $(function()
    {
		$.validator.setDefaults({
			messages: {
				required: "Pole nie zostało wypełnione, uzupełnij"
			},
            button: {
                selector: '[type="submit"]:not([formnovalidate])'
            },
			errorPlacement: function (error, element) {
				if (element.attr("type") == "checkbox") {
					error.insertAfter($(element).parent());
				} else {
					// something else if it's not a checkbox
				}
			}
		});

        $('#form-register').validate();

        function calcPrice(ile) {

            var price = $('.radio-button').filter(':checked').data('price');
 
            if($('#bon_discount').val() > 0) {
                price = price-((price*($('#bon_discount').val()))/100);
            }


            price = price*ile;
            $('#price_amount').val(price);
            $('#box_price').html(price);

            return price;
        }

        $('.pg-minus_circle').on('click', function() {
            var num = $('#ticket_num').val();
            if(num > 1) {
                $('#ticket_num').val(num-1);
                $('#box_additional_tickets').find('.box_additional_ticket_data').last().remove();

                calcPrice(num-1);
            }
        });

        $('.pg-plus_circle').on('click', function() {
            var num = parseInt($('#ticket_num').val());
            if(num < 10) {
                $('#ticket_num').val(num+1);
                var html = '<div class="box_additional_ticket_data m-t-10"><p>Podaj dane uczestnika numer ' + (num+1) + '</p>' +
                            '<div class="form-group-attached">' +
                                '<div class="row">' +
                                    '<div class="col-sm-6">' +
                                        '<div class="form-group form-group-default">' +
                                            '<label>Imię</label>' +
                                            '<input type="text" id="visitor2_firstname_' + (num+1) + '" name="visitor2_firstname[' + (num+1) + ']" placeholder="Jan" class="form-control" required>' +
                                        '</div>' +
                                    '</div>' +
                                    '<div class="col-sm-6">' +
                                        '<div class="form-group form-group-default">' +
                                            '<label>Nazwisko</label>' +
                                            '<input type="text" id="visitor2_lastname_' + (num+1) + '" name="visitor2_lastname[' + (num+1) + ']" placeholder="Kowalski" class="form-control" required>' +
                                        '</div>' +
                                    '</div>' +
                                '</div>' +
                            '</div></div>';
                $('#box_additional_tickets').find('.box_additional_ticket_data').last().after(html);

                calcPrice(num+1);
            }
        });

        $('.radio-button').on('click', function() {
            var name = $(this).data('name');
			
			if($(this).val() != 2) {
				$('#ticketBoxAdditional').hide();
				//$('#ticketBoxAdditional2').hide();
				$('.additionalCheckbox').each(function() {
					$(this).attr('checked', false);
				});
			} else {
				$('#ticketBoxAdditional').show();
				$('.additionalCheckbox').each(function() {
					$(this).trigger('click');
				});
			}

            if($('.additionalCheckbox').is(':checked')) {
				name = name + ' + udział w warsztatach';
            }

            $('#box_bilet').html(name);
            calcPrice(parseInt($('#ticket_num').val()));
        });
		
		$('#ticket_fv').on('click', function() {
			if ( $(this).is(':checked') ) {
				$('#boxFv').show();
			} else {
				$('#boxFv').hide();
				$('#visitor_company').val('');
				$('#visitor_nip').val('');
				$('#visitor_address').val('');
				$('#visitor_address2').val('');
				$('#visitor_zipcode').val('');
				$('#visitor_city').val('');
				
			}
		});
		
		

		$('.payment_type_button').on('click', function(e) {
		    e.preventDefault();
            var paymentType = $(this).attr('typeP');
            $('#payment_type').val(paymentType);
            $('#form-register').submit();
            return false;
        });

        $('.faktura_button').on('click', function(e) {
            e.preventDefault();
            var paymentType = $(this).attr('typeP');
            $('#faktura').val(paymentType);
            $('#form-register').submit();
            return false;
        });

        $('#clickHelp').on('click', function() {
            $('#boxHelp').slideToggle();
        });
		
		$('.additionalCheckbox').on('click', function() {
			if ( $(this).is(':checked') ) {
				var name = $('.radio-button').filter(':checked').data('name');
				var name = name + ' + udział w warsztatach';
			} else {
				var name = $('.radio-button').filter(':checked').data('name');
			}

			$('#box_bilet').html(name);
            //calcPrice(parseInt($('#ticket_num').val()));
		});
		
		$('#checkBon').on('click', function(e) {

		    e.preventDefault();

            $.ajax({
                method: "POST",
                url: "/ajax/visitor/bon/check",
                data: { bon_code: $('#bon_code').val() }
            }).done(function( msg ) {
                if(msg.status == 'error') {
                    $('#bonRed').html('').html(msg.komunikat);
                    $('#bonOk').html('');
                    $('#bon_id').val(0);
                    $('#bon_discount').val(0);

                } else {
                    $('#bonRed').html('');
                    $('#bonOk').html('').html('Koszt biletów został obniżony o ' + msg.bon_discount + '%');
                    $('#bon_id').val(msg.bon_id);
                    $('#bon_discount').val(msg.bon_discount);

                }

                calcPrice(parseInt($('#ticket_num').val()));
            
            });
        })

        return false;
    })
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-108264765-1"></script>
<script>
 window.dataLayer = window.dataLayer || [];
 function gtag(){dataLayer.push(arguments);}
 gtag('js', new Date());

 gtag('config', 'UA-108264765-1');
</script>
﻿<!-- Hotjar Tracking Code for http://hlshow.pl/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:709824,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

</body>
</html>
