<form role="form" id="form" action="/ajax/visitor/edit<?php if($id > 0) { ?>/<?php echo $id; } ?>" method="post">
    <input type="hidden" name="place" value="moderator" />
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label>Imię</label>
                <input id="visitor_firstname" type="text" class="form-control" value="<?php echo $result['visitor_firstname']; ?>" name="visitor_firstname">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label>Nazwisko</label>
                <input id="visitor_lastname" type="text" class="form-control" value="<?php echo $result['visitor_lastname']; ?>" name="visitor_lastname">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label>Firma</label>
                <input id="visitor_company" type="text" class="form-control" value="<?php echo $result['visitor_company']; ?>" name="visitor_company">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label>NIP</label>
                <input id="visitor_nip" type="text" class="form-control" value="<?php echo $result['visitor_nip']; ?>" name="visitor_nip">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label>Ulica</label>
                <input id="visitor_address" type="text" class="form-control" value="<?php echo $result['visitor_address']; ?>" name="visitor_address">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label>Numer</label>
                <input id="visitor_address2" type="text" class="form-control" value="<?php echo $result['visitor_address2']; ?>" name="visitor_address2">
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label>Miasto</label>
                <input id="visitor_city" type="text" class="form-control" value="<?php echo $result['visitor_city']; ?>" name="visitor_city">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label>Kod pocztowy</label>
                <input id="visitor_zipcode" type="text" class="form-control" value="<?php echo $result['visitor_zipcode']; ?>" name="visitor_zipcode">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label>Telefon</label>
                <input id="visitor_tel" type="text" class="form-control" value="<?php echo $result['visitor_tel']; ?>" name="visitor_tel">
            </div>
        </div>
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label>Email</label>
                <input id="visitor_email" type="text" class="form-control" value="<?php echo $result['visitor_email']; ?>" name="visitor_email">
            </div>
        </div>
    </div>
	<div class="row">
		<div class="col-sm-6">
            <div class="form-group form-group-default">
				<div class="checkbox checkbox-circle check-success">
					<input id="visitor_type" type="checkbox" class="" <?php if((int)$result['visitor_type'] == 2) echo 'checked="checked"'; ?> value="2" name="visitor_type">
					<label for="visitor_type">Wystawca/sponsor</label>
				</div>
            </div>
        </div>
	</div>
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group form-group-default">
                <label>Bilet</label>
                <select name="ticket_type_id" id="ticket_type_id">
					<?php foreach($ticketList as $row) { ?>
						<option value="<?php echo $row['ticket_type_id']; ?>"><?php echo $row['ticket_name']. ' - '.$row['ticket_price']; ?></option>
					<?php } ?>
				</select>
            </div>
        </div>
        <div class="col-sm-6">
			<div class="checkbox check-primary">

				<div class="checkbox check-success">
					<input type="checkbox" class="additionalCheckbox" value="1" name="additional11" id="additional11">
					<label for="additional11" style="white-space: normal">TRADING (10:00-12:30)</label>
				</div>
				<div class="checkbox check-success">
					<input type="checkbox" class="additionalCheckbox" value="1" name="additional12" id="additional12">
					<label for="additional12" style="white-space: normal">KRYPTOKOPARKI (12:30-14:45)</label>
				</div>

				<div class="checkbox check-success">
					<input type="checkbox" class="additionalCheckbox" value="1" name="additional21" id="additional21">
					<label for="additional21" style="white-space: normal">PODATKI OD KRYPTOWALUT (15:00-17:15)</label>
				</div>
            </div>
        </div>
    </div>
	<div class="row">
        <div class="col-sm-12">
			<div class="form-group form-group-default">
				<div class="checkbox checkbox-circle check-success">
					<input type="checkbox" <?php if((int)$result['ticketDarmowy'] == 1) echo 'checked="checked"'; ?> value="1" id="ticketDarmowy" name="ticketDarmowy">
					<label for="ticketDarmowy">Oznacz jako darmowy bilet</label>
				</div>
            </div>
        </div>
    </div>
</form>