<page format="A4" orientation="P" backcolor="#ffffff" style="font: arial;" backtop="0mm" backbottom="0mm" backleft="0mm" backright="0mm">
<table style="width: 100%; height: 296mm;">
    <tr style="height: 146mm;">
        <td style="width: 105mm; height: 146mm; border-right: 1px dashed #dcdbdb; text-align: center;">
            <div style="rotate: 180; margin-top: 5px">
                <div style="margin-bottom: 10px; clear: both;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT']; ?>planning/public/data/loga/logo-kariera-nowe.png" style="width: 290px;"></div>
                <div style="font-size: 30px; margin: 30px 0 35px; clear: both;"><strong><?php echo $visitor_firstname; ?> <?php echo $visitor_lastname; ?></strong></div>
                <div style="clear: both; font-size: 25px;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT'] . 'planning/public' . $visitor_qr; ?>" style="width: 130px;"><br /></div>
                <div style="text-align: center; clear: both; margin-top: 35px;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT']; ?>planning/public/data/loga/sponsorzy2.png" style="width: 400px;"></div>
            </div>
        </td>
        <td style="width: 105mm; height: 146mm; text-align: center;">
            <?php /*<div style="rotate: 180; margin-top: 5px">
                <div style="margin-bottom: 10px; clear: both;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT']; ?>planning/public/data/loga/LOGO-IT_FUTURE_EXPO2017_rgbtransparent_napis_data-copy-1.png" style="width: 190px;"></div>
                <div style="font-size: 30px; margin: 30px 0 35px; clear: both;"><strong><?php echo $visitor_firstname; ?> <?php echo $visitor_lastname; ?></strong></div>
                <div style="clear: both; font-size: 25px;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT'] . 'planning/public' . $visitor_qr; ?>" style="width: 130px;"><br /></div>
                <div style="text-align: center; clear: both; margin-top: 35px;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT']; ?>planning/public/data/loga/sponsorzy.png" style="width: 300px;"></div>
            </div>*/ ?>
        </td>
    </tr>
    <tr style="height: 146mm; width: 200mm;">
        <td style="width: 105mm; height: 146mm; border-right: 1px dashed #dcdbdb; border-top: 1px dashed #dcdbdb;">
            <?php /*<div style="text-align: center; margin-bottom: 10px; clear: both;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT']; ?>planning/public/data/loga/LOGO-IT_FUTURE_EXPO2017_rgbtransparent_napis_data-copy-1.png" style="width: 190px;"></div>
            <div style="text-align: center; font-size: 30px; margin: 30px 0 35px; clear: both;"><strong><?php echo $visitor_firstname; ?> <?php echo $visitor_lastname; ?></strong></div>
            <div style="text-align: center; clear: both; font-size: 25px;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT'] . 'planning/public' . $visitor_qr; ?>" style="width: 130px;"><br /></div>
            <div style="text-align: center; clear: both; margin-top: 35px;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT']; ?>planning/public/data/loga/sponsorzy.png" style="width: 300px;"></div>*/ ?>
        </td>
        <td style="width: 105mm; height: 146mm; border-top: 1px dashed #dcdbdb">
            <?php /*<div style="text-align: center; margin-bottom: 10px; clear: both;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT']; ?>planning/public/data/loga/LOGO-IT_FUTURE_EXPO2017_rgbtransparent_napis_data-copy-1.png" style="width: 190px;"></div>
            <div style="text-align: center; font-size: 30px;margin: 30px 0 35px; clear: both;"><strong><?php echo $visitor_firstname; ?> <?php echo $visitor_lastname; ?></strong></div>
            <div style="text-align: center; clear: both; font-size: 25px;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT'] . 'planning/public' . $visitor_qr; ?>" style="width: 130px;"><br /></div>
            <div style="text-align: center; clear: both; margin-top: 35px;"><img src="<?php echo $_SERVER['DOCUMENT_ROOT']; ?>planning/public/data/loga/sponsorzy.png" style="width: 300px;"></div>*/ ?>
        </td>
    </tr>
</table>
</page>