<!-- START SIDEBAR MENU -->
<div class="sidebar-menu">
    <!-- BEGIN SIDEBAR MENU ITEMS-->
    <ul class="menu-items">
        <li class="active open">
            <a href="javascript:;">
                <span class="title">Planowanie</span>
                <span class="active open arrow"></span></a>
            <span class="icon-thumbnail"><i class="pg-tables"></i></span>
            <ul class="sub-menu">
                <li class="">
                    <a href="/admin/planning/map">Mapa targów</a>
                    <span class="icon-thumbnail">bt</span>
                </li>
                <li class="">
                    <a href="/admin/planning/station">Stanowiska</a>
                    <span class="icon-thumbnail">dt</span>
                </li>
                <li class="">
                    <a href="/admin/planning/reservation">Rezerwacje</a>
                    <span class="icon-thumbnail">dt</span>
                </li>
            </ul>
        </li>
        <li class="">
            <a href="/admin/company"><span class="title">Firmy</span></a>
            <span class="icon-thumbnail "><i class="pg-social"></i></span>
        </li>
        <li class="">
            <a href="/admin/visitor"><span class="title">Uczestnicy</span></a>
            <span class="icon-thumbnail"><i class="pg-calender"></i></span>
        </li>
        <li class="">
            <a href="/admin/visitor/bon"><span class="title">Bony</span></a>
            <span class="icon-thumbnail"><i class="pg-calender"></i></span>
        </li>
    </ul>
    <div class="clearfix"></div>
</div>
<!-- END SIDEBAR MENU -->
